function Strontium = importStrontiumData(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  STRONTIUM = IMPORTSTRONTIUMDATA(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  STRONTIUM = IMPORTSTRONTIUMDATA(FILE, SHEET) reads from the specified
%  worksheet.
%
%  STRONTIUM = IMPORTSTRONTIUMDATA(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Strontium = importStrontiumData("/Users/nathansmac/Desktop/Strontium/Strontium.xlsx", "1_1", [4, 157]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Feb-2021 15:59:24

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    error('please input a sheet name');
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    error('please input the data lines');
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 18);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":R" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Event_num", "Time_ms_", "Amplitude", "Rise_ms_", "Decay_ms_", "Area", "Baseline", "Noise", "Group", "Channel", "x10_90Rise", "HalfWidth", "Rise50", "PeakDir", "Burst_", "BurstE_", "x10_90Slope", "RelTime"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
Strontium = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":R" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Strontium = [Strontium; tb]; %#ok<AGROW>
end

end