function pulsetestMC = importOPTOtest(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  PULSETESTMC = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  PULSETESTMC = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  PULSETESTMC = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  pulsetestMC = importfile("/Users/nathansmac/Desktop/100pA_1s/Male Control/pulsetest_MC.xlsx", "6Oct2020_C1S1R", [4, 6]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Oct-2020 20:01:55

%% Input handling
% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
	sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
	dataLines = [4, 6];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 29);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":AC" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["P1mV", "P1FileName", "P1Trace", "P1TraceStart", "P1Peak", "P1Tme", "P1RiseTimems", "P1RiseSlopepAms", "P1DecayTimems", "P1DecaySlopepAms", "P1RiseLowerPercentile", "P1RiseUpperPercentile", "P1DecayUpperPercentile", "P1DecayLowerPercentile", "P1FilePath", "P2FileName", "P2Trace", "P2TraceStart", "P2Peak", "P2Tme", "P2RiseTimems", "P2RiseSlopepAms", "P2DecayTimems", "P2DecaySlopepAms", "P2RiseLowerPercentile", "P2RiseUpperPercentile", "P2DecayUpperPercentile", "P2DecayLowerPercentile", "P2FilePath"];
opts.VariableTypes = ["double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify variable properties
opts = setvaropts(opts, ["P1FileName", "P1FilePath", "P2FileName", "P2FilePath"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["P1FileName", "P1FilePath", "P2FileName", "P2FilePath"], "EmptyFieldRule", "auto");

% Import the data
pulsetestMC = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
	opts.DataRange = "A" + dataLines(idx, 1) + ":AC" + dataLines(idx, 2);
	tb = readtable(workbookFile, opts, "UseExcel", false);
	pulsetestMC = [pulsetestMC; tb]; %#ok<AGROW>
end
end