function RMP = importRMP(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  RMP = IMPORTRMP(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
%  table.
%
%  RMP = IMPORTRMP(FILE, SHEET) reads from the specified worksheet.
%
%  RMP = IMPORTRMP(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  RMP = importRMP("/Users/nathansmac/Desktop/LH2VTA/GABA_Firing/100pA_1s/RMP.xlsx", "Male_Control", [2, 11]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Nov-2020 11:40:43

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 11];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":G" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["CellName", "FileName", "Trace", "TraceStart", "AverageRMPmV", "FilePath", "APs", "Index"];
opts.VariableTypes = ["string", "string", "double", "double", "double", "categorical", "categorical", "string"];

% Specify variable properties
opts = setvaropts(opts, ["CellName", "FileName"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["CellName", "FileName", "FilePath", "APs"], "EmptyFieldRule", "auto");

% Import the data
RMP = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":G" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    RMP = [RMP; tb]; %#ok<AGROW>
end

end