function tableRange = importRANGE(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  tableRange = importRANGE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  tableRange = importRANGE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  tableRange = importRANGE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  tableRangeFiring = importRANGE("/Users/nathansmac/Desktop/LH2VTA/GABA_Firing/tableRange_Firing.xlsx", "MaleControl", [2, 4]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Sep-2020 11:25:36

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 4];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":D" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Tab_Names", "StepRange", "StimRange", "OptoRange"];
opts.SelectedVariableNames = ["Tab_Names", "StepRange", "StimRange", "OptoRange"];
opts.VariableTypes = ["string", "string", "string", "string"];
%opts.CategoryNames = 
opts = setvaropts(opts, [1, 2, 3, 4], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 4], "EmptyFieldRule", "auto");

% Import the data
tableRange = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":D" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    tableRange = [tableRange; tb]; %#ok<AGROW>
end

end